repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks.git
      rev: v4.4.0
      hooks:
          - id: check-json
          - id: check-yaml
          - id: check-merge-conflict
          - id: detect-private-key
          - id: check-added-large-files

    - repo: https://github.com/dnephin/pre-commit-golang
      rev: v0.5.1
      hooks:
          - id: go-imports
          - id: go-mod-tidy
          - id: golangci-lint

    # - repo: https://github.com/golangci/golangci-lint
    #   rev: v1.51.2
    #   hooks:
    #       - id: golangci-lint
